#!/bin/bash
# sync-aliases.sh — Regenerate /etc/smtpd/aliases from agents group membership
#
# Usage: sync-aliases.sh
#
# This script:
#   1. Reads all members of the 'agents' group
#   2. Generates the 'all' group alias (delivers to every agent)
#   3. Merges in custom aliases from /etc/smtpd/aliases.static (if present)
#   4. Writes the result to /etc/smtpd/aliases
#
# Called automatically by create-agent.sh, remove-agent.sh, agent-manager.sh,
# and soft-reset.sh. Can also be run manually to regenerate aliases.

set -euo pipefail

# --- Host/container detection ---
# If not running inside the container, proxy the command through docker exec.
# Override the container name with AGENT_HOST_CONTAINER if needed.
if [[ ! -f /.dockerenv ]]; then
    CONTAINER="${AGENT_HOST_CONTAINER:-agent-host}"
    exec docker exec "$CONTAINER" /usr/local/bin/"$(basename "$0")" "$@"
fi

readonly ALIASES_FILE="/etc/smtpd/aliases"
readonly STATIC_FILE="/etc/smtpd/aliases.static"

# Get all members of the 'agents' group
AGENTS_MEMBERS=$(getent group agents 2>/dev/null | cut -d: -f4 | tr ',' ' ')

# Build the aliases file
{
    echo "# Auto-generated by sync-aliases.sh — do not edit manually"
    echo "# Regenerated whenever agents are added or removed"
    echo "#"
    echo "# To add custom aliases, edit /etc/smtpd/aliases.static"
    echo "# (source: config/smtpd/aliases.static in the repo)"
    echo ""

    # Standard system aliases
    echo "# System aliases"
    echo "postmaster: root"
    echo ""

    # Group alias: 'all' delivers to every agent
    if [[ -n "$AGENTS_MEMBERS" ]]; then
        # Build comma-separated list
        ALL_LIST=""
        for USERNAME in $AGENTS_MEMBERS; do
            if [[ -n "$ALL_LIST" ]]; then
                ALL_LIST="${ALL_LIST}, ${USERNAME}"
            else
                ALL_LIST="$USERNAME"
            fi
        done
        echo "# Group alias — delivers to all agents"
        echo "all: ${ALL_LIST}"
    else
        echo "# Group alias — no agents registered"
        echo "# all: (empty — create agents to populate)"
    fi

    # Merge in static custom aliases
    if [[ -f "$STATIC_FILE" ]]; then
        echo ""
        echo "# Custom aliases (from aliases.static)"
        # Include non-comment, non-empty lines
        grep -v '^\s*#' "$STATIC_FILE" | grep -v '^\s*$' || true
    fi
} > "$ALIASES_FILE"

echo "sync-aliases: Updated $ALIASES_FILE"
if [[ -n "$AGENTS_MEMBERS" ]]; then
    echo "sync-aliases: all -> ${AGENTS_MEMBERS}"
else
    echo "sync-aliases: No agents registered"
fi
