#!/bin/bash
# sync-aliases.sh — Regenerate /etc/smtpd/aliases from agents group membership
#
# Usage: sync-aliases.sh
#
# This script:
#   1. Reads all members of the 'agents' group
#   2. Generates the 'all' group alias (delivers to everyone)
#   3. Generates per-persona aliases (e.g., coder-all, manager-all)
#   4. Merges in custom aliases from /etc/smtpd/aliases.static (if present)
#   5. Writes the result to /etc/smtpd/aliases
#
# Called automatically by create-agent.sh, remove-agent.sh, agent-manager.sh,
# and soft-reset.sh. Can also be run manually to regenerate aliases.

set -euo pipefail

# --- Host/container detection ---
# If not running inside the container, proxy the command through docker exec.
# Override the container name with AGENT_HOST_CONTAINER if needed.
if [[ ! -f /.dockerenv ]]; then
    CONTAINER="${AGENT_HOST_CONTAINER:-agent-host}"
    exec docker exec "$CONTAINER" /usr/local/bin/"$(basename "$0")" "$@"
fi

readonly ALIASES_FILE="/etc/smtpd/aliases"
readonly STATIC_FILE="/etc/smtpd/aliases.static"
readonly PERSONAS_DIR="/etc/agent-personas"

# Get all members of the 'agents' group
AGENTS_MEMBERS=$(getent group agents 2>/dev/null | cut -d: -f4 | tr ',' ' ')

# Build the aliases file
{
    echo "# Auto-generated by sync-aliases.sh — do not edit manually"
    echo "# Regenerated whenever users are added or removed"
    echo "#"
    echo "# To add custom aliases, edit /etc/smtpd/aliases.static"
    echo "# (source: config/smtpd/aliases.static in the repo)"
    echo ""

    # Standard system aliases
    echo "# System aliases"
    echo "postmaster: root"
    echo ""

    # Group alias: 'all' delivers to everyone
    if [[ -n "$AGENTS_MEMBERS" ]]; then
        # Build comma-separated list
        ALL_LIST=""
        for USERNAME in $AGENTS_MEMBERS; do
            if [[ -n "$ALL_LIST" ]]; then
                ALL_LIST="${ALL_LIST}, ${USERNAME}"
            else
                ALL_LIST="$USERNAME"
            fi
        done
        echo "# Group alias — delivers to everyone"
        echo "all: ${ALL_LIST}"
    else
        echo "# Group alias — no users registered"
        echo "# all: (empty — create users to populate)"
    fi

    # Per-persona aliases: <persona>-all delivers to everyone with that persona
    # Discover persona groups by checking which persona names have a matching Unix group
    PERSONA_ALIASES_FOUND=false
    if [[ -d "$PERSONAS_DIR" ]]; then
        for PERSONA_FILE in "$PERSONAS_DIR"/*.md; do
            [[ -f "$PERSONA_FILE" ]] || continue
            PERSONA_NAME=$(basename "$PERSONA_FILE" .md)
            [[ "$PERSONA_NAME" == "base" ]] && continue

            # Check if a Unix group exists for this persona
            MEMBERS=$(getent group "$PERSONA_NAME" 2>/dev/null | cut -d: -f4 | tr ',' ' ')
            [[ -z "$MEMBERS" ]] && continue

            if [[ "$PERSONA_ALIASES_FOUND" == false ]]; then
                echo ""
                echo "# Persona aliases — <persona>-all delivers to everyone with that role"
                PERSONA_ALIASES_FOUND=true
            fi

            MEMBER_LIST=""
            for USERNAME in $MEMBERS; do
                if [[ -n "$MEMBER_LIST" ]]; then
                    MEMBER_LIST="${MEMBER_LIST}, ${USERNAME}"
                else
                    MEMBER_LIST="$USERNAME"
                fi
            done
            echo "${PERSONA_NAME}-all: ${MEMBER_LIST}"
        done
    fi

    # Merge in static custom aliases
    if [[ -f "$STATIC_FILE" ]]; then
        echo ""
        echo "# Custom aliases (from aliases.static)"
        # Include non-comment, non-empty lines
        grep -v '^\s*#' "$STATIC_FILE" | grep -v '^\s*$' || true
    fi
} > "$ALIASES_FILE"

echo "sync-aliases: Updated $ALIASES_FILE"
if [[ -n "$AGENTS_MEMBERS" ]]; then
    echo "sync-aliases: all -> ${AGENTS_MEMBERS}"
else
    echo "sync-aliases: No users registered"
fi
