#!/bin/bash
# sync-api-keys.sh — Sync environment variables to global API keys file
#
# This script runs at container boot to write any API key environment
# variables from the host into /etc/agent-api-keys/global.env
#
# It merges:
#   1. Static config from /etc/agent-api-keys/global.env.static (if exists)
#   2. Environment variables passed via docker-compose
#
# This allows users to either:
#   - Set API keys in config/api-keys/global.env (baked into image)
#   - Pass API keys via host environment variables (runtime)

set -euo pipefail

echo "sync-api-keys: Starting at $(date -Iseconds)"

readonly API_KEYS_DIR="/etc/agent-api-keys"
readonly GLOBAL_ENV="${API_KEYS_DIR}/global.env"
readonly STATIC_ENV="${API_KEYS_DIR}/global.env.static"

# Known API key environment variable names
readonly KNOWN_KEYS=(
    "ANTHROPIC_API_KEY"
    "OPENAI_API_KEY"
    "GOOGLE_API_KEY"
    "GEMINI_API_KEY"
    "MISTRAL_API_KEY"
    "COHERE_API_KEY"
    "GROQ_API_KEY"
    "TOGETHER_API_KEY"
    "FIREWORKS_API_KEY"
    "PERPLEXITY_API_KEY"
    "REPLICATE_API_TOKEN"
    "HUGGINGFACE_API_KEY"
    "HF_TOKEN"
    "AWS_ACCESS_KEY_ID"
    "AWS_SECRET_ACCESS_KEY"
    "AWS_DEFAULT_REGION"
    "AZURE_OPENAI_API_KEY"
    "AZURE_OPENAI_ENDPOINT"
)

# Ensure directory exists
echo "sync-api-keys: Ensuring ${API_KEYS_DIR} exists..."
mkdir -p "$API_KEYS_DIR"

# Start with header
echo "sync-api-keys: Writing keys to ${GLOBAL_ENV}..."
{
    echo "# Global API Keys"
    echo "# Auto-generated by sync-api-keys.sh at $(date -Iseconds)"
    echo "# Do not edit - changes will be overwritten on container restart"
    echo ""

    # First, include any static config (from baked-in global.env)
    echo "sync-api-keys: Checking for static config at ${STATIC_ENV}..." >&2
    if [[ -f "$STATIC_ENV" ]]; then
        echo "sync-api-keys: Loading static config..." >&2
        echo "# --- From static config ---"
        while IFS='=' read -r key value; do
            # Skip comments and empty lines
            [[ "$key" =~ ^[[:space:]]*# ]] && continue
            [[ -z "$key" ]] && continue
            key="$(echo "$key" | xargs)"
            echo "${key}=${value}"
        done < "$STATIC_ENV"
        echo ""
    else
        echo "sync-api-keys: No static config found." >&2
    fi

    echo "sync-api-keys: Scanning environment for API keys..." >&2
    echo "# --- From environment variables ---"

    # Check each known key in the environment
    for key in "${KNOWN_KEYS[@]}"; do
        value="${!key:-}"
        if [[ -n "$value" ]]; then
            echo "${key}=${value}"
        fi
    done
} > "$GLOBAL_ENV"

# Secure permissions
echo "sync-api-keys: Setting permissions on ${GLOBAL_ENV}..."
chmod 644 "$GLOBAL_ENV"
chown root:root "$GLOBAL_ENV"

# Count how many keys were written
key_count=$(grep -c '^[A-Z]' "$GLOBAL_ENV" 2>/dev/null || echo "0")
echo "sync-api-keys: Wrote ${key_count} API key(s) to ${GLOBAL_ENV}"
echo "sync-api-keys: Finished at $(date -Iseconds)"
